---

version: '3'

services:
  test-saml:
    image: kristophjunge/test-saml-idp
    container_name: samlify_test-saml-idp
    restart: always
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=saml-poc
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:4300/login/callback
